<# 
 .Synopsis
  Print out the ContainerHelper WelCome text
#>
function Write-BcContainerHelperWelcomeText {
    Clear-Host
    Write-Host -ForegroundColor Yellow "Welcome to the Business Central container Helper PowerShell Prompt"
    Write-Host
    Write-Host -ForegroundColor Yellow "Container info functions"
    Write-Host "Get-BcContainerNavVersion       Get Nav version from Business Central container or image"
    Write-Host "Get-BcContainerImageName        Get ImageName from Business Central container"
    Write-Host "Get-BcContainerGenericTag       Get Nav generic image tag from Business Central container or image"
    Write-Host "Get-BcContainerOsVersion        Get OS version from Business Central container or image"
    Write-Host "Get-BcContainerEula             Get Eula link from Business Central container or image"
    Write-Host "Get-BcContainerLegal            Get Legal link from Business Central container or image"
    Write-Host "Get-BcContainerCountry          Get country version from Business Central container or image"
    Write-Host "Get-BcContainerIpAddress        Get IP Address to a Business Central container"
    Write-Host "Get-BcContainerSharedFolders    Get Shared Folders from a Business Central container"
    Write-Host "Get-BcContainerPath             Get the path inside a Business Central container to a shared file"
    Write-Host "Get-BcContainerName             Get the name of a Business Central container"
    Write-Host "Get-BcContainerId               Get the Id of a Business Central container"
    Write-Host "Test-BcContainer                Test whether a Business Central container exists"
    Write-Host "Get-BcContainerDebugInfo        Get Troubleshooting info for Business Central container if you need help with an issue"
    Write-Host "Get-BcContainers                Get All Business Central containers"
    Write-Host "Get-BcContainerEventLog         Get EventLog from Business Central container"
    Write-Host "Get-BcContainerServerConfiguration Get Server Configuration from Business Central container"
    Write-Host
    Write-Host -ForegroundColor Yellow "Container handling functions"
    Write-Host "New-BcContainer                 Create new Business Central container"
    Write-Host "Remove-BcContainer              Remove Business Central container"
    Write-Host "Stop-BcContainer                Stop Business Central container"
    Write-Host "Start-BcContainer               Start Business Central container"
    Write-Host "Restart-BcContainer             Restart Business Central container"
    Write-Host "Import-BcContainerLicense       Import License to a Business Central container"
    Write-Host "Get-BcContainerSession          Create new session to a Business Central container"
    Write-Host "Remove-BcContainerSession       Remove Business Central container session"
    Write-Host "Enter-BcContainer               Enter Business Central container session"
    Write-Host "Open-BcContainer                Open Business Central container in new window"
    Write-Host "Wait-BcContainerReady           Wait for Business Central container to become ready"
    Write-Host "Copy-FileFromBcContainer        Copy file from Business Central container"
    Write-Host "Copy-FileToBcContainer          Copy file to Business Central container"
    Write-Host "Export-BcContainerDatabasesAsBacpac Export database(s) in Business Central container as BacPac"
    Write-Host "Backup-BcContainerDatabases     Backup database(s) in Business Central container as bak"
    Write-Host "Extract-FilesFromBcContainerImage Extract files from Business Central container Image"
    Write-Host "Get-BestBcContainerImageName    Get best specific Business Central container Image for your host OS"
    Write-Host
    Write-Host -ForegroundColor Yellow "Functions for running tests"
    Write-Host "Import-TestToolkitToBcContainer Import TestToolkit to Business Central container"
    Write-Host "Get-TestsFromBcContainer        Get a list of tests from a Business Central Container"
    Write-Host "Run-TestsInBcContainer          Run Tests inside a Business Central container"
    Write-Host
    Write-Host -ForegroundColor Yellow "Object handling functions (NAV)"
    Write-Host "Import-ObjectsToNavContainer    Import objects from .txt or .fob file to NAV container"
    Write-Host "Import-DeltasToNavContainer     Merge delta files and Import objects to NAV container"
    Write-Host "Compile-ObjectsInNavContainer   Compile objects"
    Write-Host "Export-NavContainerObjects      Export objects from NAV container"
    Write-Host "Create-MyOriginalFolder         Create folder with the original objects for modified objects"
    Write-Host "Create-MyDeltaFolder            Create folder with deltas for modified objects"
    Write-Host "Convert-Txt2Al                  Convert deltas folder to al folder"
    Write-Host "Export-ModifiedObjectsAsDeltas  Export objects, create baseline and create deltas"
    Write-Host "Convert-ModifiedObjectsToAl     Export objects, create baseline, create deltas and convert to .al files"
    Write-Host "Invoke-NavContainerCodeunit     Invoke Codeunit in NAV container"
    Write-Host
    Write-Host -ForegroundColor Yellow "App handling functions"
    Write-Host "Compile-AppInBcContainer        Use Container to compile App"
    Write-Host "Publish-BcContainerApp          Publish App to Business Central container"
    Write-Host "Sync-BcContainerApp             Sync App in Business Central container"
    Write-Host "Install-BcContainerApp          Install App in Business Central container"
    Write-Host "Uninstall-BcContainerApp        Uninstall App from Business Central container"
    Write-Host "Unpublish-BcContainerApp        Unpublish App from Business Central container"
    Write-Host "Get-BcContainerAppInfo          Get info about installed apps from Business Central container"
    Write-Host "Start-BcContainerAppDataUpgrade Start Data Upgrade for an App in a Business Central container"
    Write-Host "Install-NAVSipCryptoProviderFromBcContainer Install Nav Sip Crypto Provider locally from container to sign extensions"
    Write-Host "Sign-BcContainerApp             Uses a Business Central container to sign an App"
    Write-Host
    Write-Host -ForegroundColor Yellow "Tenant handling functions"
    Write-Host "Get-BcContainerTenants          Get all tenants in Business Central container"
    Write-Host "New-BcContainerTenant           Create tenant in multitenant Business Central container"
    Write-Host "Remove-BcContainerTenant        Remove tenant from multitenant Business Central container"
    Write-Host 
    Write-Host -ForegroundColor Yellow "User handling functions"
    Write-Host "Get-BcContainerBcUser           Get all users in Business Central container"
    Write-Host "New-BcContainerBcUser           Create new Nav User in Business Central container"
    Write-Host "New-BcContainerWindowsUser      Create new Windows User in Business Central container"
    Write-Host "Setup-BcContainerTestUsers      Create a set of users for test purposes"
    Write-Host 
    Write-Host -ForegroundColor Yellow "Company handling functions"
    Write-Host "Get-CompanyInBcContainer        Get a list of Companies in Business Central container"
    Write-Host "New-CompanyInBcContainer        Create new Company in Business Central container"
    Write-Host "Remove-CompanyInBcContainer     Remove Company from Business Central container"
    Write-Host 
    Write-Host -ForegroundColor Yellow "Configuration package handling functions"
    Write-Host "Import-ConfigPackageInBcContainer Import Configuration package in Business Central container"
    Write-Host "Remove-ConfigPackageInBcContainer Remove Configuratioin package from Business Central container"
    Write-Host 
    Write-Host -ForegroundColor Yellow "Azure AD specific functions"
    Write-Host "Create-AadAppsForNav             Create Apps in Aad for AAD authentication support"
    Write-Host "Create-AadUsersInBcContainer    Create all active users in the Aad in the Business Central container"
    Write-Host
    Write-Host -ForegroundColor Yellow "Azure VM specific functions"
    Write-Host "Replace-BcServerContainer        Replace or recreate bcserver (primary) container"
    Write-Host "New-LetsEncryptCertificate       Create Lets Encrypt Certificate for secure communication"
    Write-Host "Renew-LetsEncryptCertificate     Renew Lets Encrypt Certificate for secure communication"
    Write-Host
    Write-Host -ForegroundColor White "Note: The BcContainerHelper is an open source project from http://www.github.com/microsoft/NavContainerhelper."
    Write-Host -ForegroundColor White "The project is released as-is, no warranty! Contributions are welcome, study the github repository for usage."
    Write-Host -ForegroundColor White "Report issues on http://www.github.com/microsoft/NavContainerhelper/issues."
    Write-Host
}
Export-ModuleMember -Function Write-BcContainerHelperWelcomeText
