trigger: none
name: Release BCContainerHelper (Preview) $(Date:yyyyMMdd).$(Rev:r)
pr: none

resources:
  repositories:
  - repository: onebranchTemplates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
variables:
  - name: WindowsContainerImage
    value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@onebranchTemplates
  parameters:
    featureFlags:
      WindowsHostVersion:
        Version: 2022
        Network: R1
    stages:
    - stage: PrepareModule
      displayName: 'Prepare BcContainerHelper'
      jobs:
      - job: PrepareModule
        displayName: 'Prepare Module'
        pool:
          type: 'windows'
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        - name: ob_artifactBaseName
          value: drop_build
        steps:
        - checkout: self
          displayName: 'Checkout'

        - task: PowerShell@2
          displayName: 'Prepare Module'
          inputs:
            targetType: 'inline'
            pwsh: false
            script: |
              $errorActionPreference = "stop"
              try {
                $path = Join-Path $(Build.StagingDirectory) "module\BcContainerHelper"
                New-Item -path $path -itemType Directory -Force | Out-Null

                Write-Host "Copying files to $path"
                $filesPath = Join-Path $(Build.SourcesDirectory) "navcontainerhelper"
                Get-ChildItem -Path $filesPath -Recurse | ForEach-Object { Write-Host $_.FullName }
                Copy-Item -Path (Join-Path $filesPath "*") -Destination $path -Recurse -Force

                Remove-Item -Path (Join-Path $path "Tests") -Force -Recurse -ErrorAction Ignore
                Remove-Item -Path (Join-Path $path ".github") -Force -Recurse -ErrorAction Ignore
                Remove-Item -Path (Join-Path $path ".azuredevops") -Force -Recurse -ErrorAction Ignore
                Remove-Item -Path (Join-Path $path ".git") -Force -Recurse -ErrorAction Ignore
                Remove-Item -Path (Join-Path $path ".gitignore") -Force -ErrorAction Ignore
                Remove-Item -Path (Join-Path $path "README.md") -Force -ErrorAction Ignore

                $versionFile = Join-Path $path 'Version.txt'
                $version = (Get-Content -Path $versionFile).split('-')[0]
                Write-Host "BcContainerHelper version $Version"
                Set-Content -Path $versionFile -Value $version

                $modulePath = Join-Path $filesPath "BcContainerHelper.psm1"
                Import-Module $modulePath -DisableNameChecking

                $functionsToExport = (Get-Module -Name BcContainerHelper).ExportedFunctions.Keys | Sort-Object
                $aliasesToExport = (Get-Module -Name BcContainerHelper).ExportedAliases.Keys | Sort-Object

                $labels = Get-BcContainerImageLabels -imageName 'mcr.microsoft.com/businesscentral:ltsc2022'
                Write-Host "Set latest generic tag version to $($labels.tag)"
                Set-Content -Path (Join-Path $path 'LatestGenericTagVersion.txt') -value $labels.tag

                $releaseNotes = Get-Content -Path (Join-Path $path "ReleaseNotes.txt")
                $idx = $releaseNotes.IndexOf($version)
                if ($idx -lt 0) {
                    throw 'No release notes identified'
                }
                $versionReleaseNotes = @()
                while ($releaseNotes[$idx]) {
                    $versionReleaseNotes += $releaseNotes[$idx]
                    $idx++
                }

                Write-Host "Release Notes:"
                Write-Host $VersionReleaseNotes

                Write-Host "Update Module Manifest"
                Update-ModuleManifest -Path (Join-Path $path "BcContainerHelper.psd1") `
                                      -RootModule "BcContainerHelper.psm1" `
                                      -ModuleVersion $version `
                                      -Author "Freddy Kristiansen" `
                                      -FunctionsToExport $functionsToExport `
                                      -AliasesToExport $aliasesToExport `
                                      -CompanyName "Microsoft" `
                                      -ReleaseNotes $versionReleaseNotes `
                                      -LicenseUri 'https://github.com/microsoft/navcontainerhelper/blob/main/LICENSE' `
                                      -ProjectUri 'https://github.com/microsoft/navcontainerhelper'

              }
              catch {
                Write-Host "##vso[task.logissue type=error]Error preparing module. Error was: $($_.Exception.Message)"
                exit 1
              }

        - task: onebranch.pipeline.signing@1 # https://aka.ms/obpipelines/signing
          displayName: 'Sign PowerShell Files'
          inputs:
            command: 'sign'
            signing_profile: 'external_default'
            files_to_sign: '**\*.ps1;**\*.psm1;**\*.psd1'
            search_root: '$(Build.StagingDirectory)\module\BcContainerHelper'

    - stage: DeployToStorage
      displayName: 'Deploy to Azure Storage'
      dependsOn: ['PrepareModule']
      condition: succeeded()
      jobs:
      - job: UploadToStorage
        displayName: 'Upload to Storage Account'
        pool:
          type: 'windows'
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        - name: ob_artifactBaseName
          value: drop_build
        steps:
        - download: current
          artifact: 'BcContainerHelper'
          displayName: 'Download BcContainerHelper Artifact'

        - task: PowerShell@2
          displayName: 'Publish to PowerShell Gallery'
          inputs:
            targetType: 'inline'
            pwsh: true
            script: |
              Write-Host "Upload to Azure Storage is currently disabled. Please enable and configure the following script when ready." # TODO: Remove this line when enabling the script below.

        # - task: AzureCLI@2
        #   displayName: 'Upload to Azure Storage'
        #   inputs:
        #     azureSubscription: 'BcContainerHelper-ServiceConnection'
        #     scriptType: 'pscore'
        #     scriptLocation: 'inlineScript'
        #     inlineScript: |
        #       $storageAccountName = "bccontainerhelper"  # TODO: Update with actual storage account name
        #       $containerName = "modules"  # TODO: Update with actual container name
        #       $modulePath = "$(Pipeline.Workspace)/BcContainerHelper"

        #       $versionFile = Join-Path $modulePath 'BcContainerHelper/Version.txt'
        #       $version = Get-Content -Path $versionFile
        #       Write-Host "Uploading BcContainerHelper version $version to Azure Storage"

        #       # Create a zip file of the module
        #       $zipPath = "$(Pipeline.Workspace)/BcContainerHelper-$version.zip"
        #       Compress-Archive -Path "$modulePath/*" -DestinationPath $zipPath -Force

        #       # Upload to Azure Storage
        #       az storage blob upload `
        #         --account-name $storageAccountName `
        #         --container-name $containerName `
        #         --name "BcContainerHelper-$version.zip" `
        #         --file $zipPath `
        #         --auth-mode login `
        #         --overwrite

        #       Write-Host "Successfully uploaded to Azure Storage"

    - stage: DeployToPSGallery
      displayName: 'Deploy to PowerShell Gallery'
      dependsOn: ['PrepareModule']
      condition: succeeded()
      jobs:
      - job: PublishToPSGallery
        displayName: 'Publish to PowerShell Gallery'
        pool:
          type: 'windows'
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        - name: ob_artifactBaseName
          value: drop_build
        steps:
        - download: current
          artifact: 'BcContainerHelper'
          displayName: 'Download BcContainerHelper Artifact'

        - task: PowerShell@2
          displayName: 'Publish to PowerShell Gallery'
          inputs:
            targetType: 'inline'
            pwsh: true
            script: |
              $errorActionPreference = "stop"
              try {
                $modulePath = "$(Pipeline.Workspace)/BcContainerHelper/BcContainerHelper"
                $versionFile = Join-Path $modulePath 'Version.txt'
                $version = Get-Content -Path $versionFile
                Write-Host "Publishing BcContainerHelper version $version to PowerShell Gallery"

                # Get the API key from pipeline variable
                $apiKey = $env:PSGALLERY_API_KEY
                if (-not $apiKey) {
                  throw "PowerShell Gallery API key not found. Please set the PSGALLERY_API_KEY variable."
                }

                # Publish to PowerShell Gallery
                Publish-Module -Path $modulePath -NuGetApiKey $apiKey -Repository PSGallery -Verbose

                Write-Host "Successfully published to PowerShell Gallery"
              }
              catch {
                Write-Host "##vso[task.logissue type=error]Error publishing to PowerShell Gallery. Error was $($_.Exception.Message)"
                exit 1
              }
          env:
            PSGALLERY_API_KEY: $(PSGalleryApiKey)