trigger: none
name: Release BCContainerHelper (Production - ${{ parameters.ProductionRelease }} ) - $(Date:yyyy).$(Date:MM).$(Date:dd)-$(Rev:.r)
pr: none

resources:
  repositories:
  - repository: onebranchTemplates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
  - repository: PipelineTemplates
    type: git
    name: Infrastructure-PipelineTemplates
    ref: master

variables:
  - name: WindowsContainerImage
    value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
  - ${{ if eq(parameters.TestRun, false) }}:
    - template: codesign-variables.yml@PipelineTemplates

parameters:
  - name: ProductionRelease
    displayName: Production Release
    type: boolean
    default: false
  - name: TestRun
    displayName: Test Run (no signing, no PSGallery deployment, Storage upload only to test storage)
    type: boolean
    default: false

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@onebranchTemplates
  parameters:
    globalSdl: # https://aka.ms/obpipelines/sdl
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)/.azuredevops/pipelines/CredScanSuppressions.json
    featureFlags:
      WindowsHostVersion: '1ESWindows2022'
    stages:
    - stage: PrepareModule
      displayName: 'Prepare BcContainerHelper'
      jobs:
      - job: PrepareModule
        displayName: 'Prepare BCContainerHelper Module'
        pool:
          type: 'windows'
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/module'
        - name: ob_artifactBaseName
          value: BCContainerHelper_Module
        steps:
        - task: PowerShell@2
          displayName: 'Prepare Module'
          inputs:
            targetType: 'filePath'
            filePath: '$(Build.SourcesDirectory)/.azuredevops/scripts/PrepareBCContainerHelperModule.ps1'
            arguments: "-OutputPath '$(ob_outputDirectory)' -ProductionRelease:([bool]::Parse('${{ parameters.ProductionRelease }}'))"
            pwsh: false
        - ${{ if eq(parameters.TestRun, false) }}:
          - template: codesign.yml@PipelineTemplates
            parameters:
              OutputPath: '$(ob_outputDirectory)'

    - stage: DeployToStorage
      displayName: 'Deploy to Azure Storage'
      dependsOn: ['PrepareModule']
      variables:
        - ${{ if eq(parameters.TestRun, false) }}:
          - name: AzureStorageContainer
            value: 'public'
        - ${{ if eq(parameters.TestRun, true) }}:
          - name: AzureStorageContainer
            value: 'test'
      jobs:
      - job: UploadToStorage
        displayName: 'Upload to Storage Account'
        pool:
          type: 'windows'
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/zip'
        - name: ob_artifactBaseName
          value: BCContainerHelper_Zip
        steps:
        - download: current
          artifact: BCContainerHelper_Module
          displayName: 'Download BcContainerHelper Artifact'

        - task: PowerShell@2
          displayName: 'Create Zip File of Module'
          inputs:
            targetType: 'filePath'
            filePath: '$(Build.SourcesDirectory)/.azuredevops/scripts/CreateZipFile.ps1'
            arguments: "-ModulePath '$(Pipeline.Workspace)/BCContainerHelper_Module' -OutputDirectory '$(ob_outputDirectory)'"
            pwsh: true

        - task: AzureCLI@2
          displayName: 'Upload to Azure Storage'
          inputs:
            azureSubscription: 'NAVDocker-PartnerArtifacts'
            scriptType: 'pscore'
            scriptLocation: 'scriptPath'
            scriptPath: '$(Build.SourcesDirectory)/.azuredevops/scripts/UploadToAzureStorage.ps1'
            arguments: "-StorageAccountName 'bccontainerhelper' -ContainerName '$(AzureStorageContainer)' -ZipPath '$(BCContainerHelperZipPath)' -Version '$(BCContainerHelperVersion)' -IsProductionRelease:([bool]::Parse('${{ parameters.ProductionRelease }}'))"

    - stage: DeployToPSGallery
      displayName: 'Deploy to PowerShell Gallery'
      dependsOn: ['PrepareModule']
      condition: and(succeeded(), ${{ eq(parameters.TestRun, false) }})
      jobs:
      - job: PublishToPSGallery
        displayName: 'Publish to PowerShell Gallery'
        pool:
          type: 'windows'
        variables:
          - name: ob_outputDirectory
            value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
          - name: ob_artifactBaseName
            value: BCContainerHelper_PSGallery
        steps:
        - download: current
          artifact: BCContainerHelper_Module
          displayName: 'Download BcContainerHelper Artifact'

        - task: PowerShell@2
          displayName: 'Publish to PowerShell Gallery'
          inputs:
            targetType: 'inline'
            pwsh: true
            script: |
              $errorActionPreference = "stop"
              try {
                $modulePath = "$(Pipeline.Workspace)/BCContainerHelper_Module"

                $apiKey = "TOODO: Replace me"
                if (-not $apiKey) {
                  throw "PowerShell Gallery API key not found"
                }

                # Publish to PowerShell Gallery
                Register-PSRepository -Default # Ensure the default repository is registered, PSGallery
                Publish-Module -Path $modulePath -NuGetApiKey $apiKey -SkipAutomaticTags

                Write-Host "Successfully published to PowerShell Gallery"
              }
              catch {
                Write-Host "##vso[task.logissue type=error]Error publishing to PowerShell Gallery. Error was $($_.Exception.Message)"
                exit 1
              }
