name: Mark stale issues

on:
  workflow_dispatch:
  schedule:
  - cron: '44 5 * * 1' # Monday, 5:44 (UTC)

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
      with:
        stale-issue-label: 'stale'
        days-before-issue-stale: 180
        days-before-issue-close: 14
        close-issue-message: 'There has been no recent activity on this issue. Please re-open or create a new issue, if needed.'
